application/json:
  example: |
    {
      //Идентификатор пользователя: string, required
      "id": "BF4585465460D",
      //Идентификатор акции: string, required
      "id_event": "DFFG4fG44DD",
      //Идентификатор города: number, required
      "id_city": 1
    }
