application/json:
  example: |
    {
      //Идентификатор устройства: string, required
      "id_device": "BF4585465460D",
      //Тип операционной системы: string, required
      "os": "anroid",
      //Версия приложения: string, required
      "version_app": "version_app",
      //Токен: string, required
      "token": "GFDFgfd00D",
      //Ключ: string, required
      "key": "12565D565".
      //Идентификатор города: number, required
      "id_city": 1
    }
