application/json:
  example: |
    {
      //Идентификатор пользователя: string, required
      "id": "BF4585465460D",
      //Идентификатор акции: string
      "id_event": "DGSFDSSS",
      //Идентификатор города: number
      "id_city": 1
    }
