description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат обработки отправки ознакомления с условиями: true - отправка успешна, false - пользователь уже когда-то ознакамливался с условиями акции: bool
          "success": "true"
        }
      }
