application/json:
  example: |
    {
      //Идентификатор пользователя: string, required
      "id": "BF4585465460D",
      //Идентификатор города: number, required
      "id_city": 1,
      //Тип операционной системы приложения: string, required
      "os": "android",
      //Версия приложения: string, required
      "version_app": "1.0.0.0"
    }
