description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат проверки версии приложения: true - приложение поддерживается, false - нет: bool
          "succces": true,
          //Текущая версия приложения: string
          "version_app": "1.0.0.0"
        }
      }
