description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
            //Результат проведения операции сохранения настроек пользователя: true - успешна, false - нет: bool
            "success": true
        }
      }
