application/json:
  example: |
    {
      //Идентификатор пользователя: string, required
      "id": "BF4585465460D",
      //Идентификатор города: number, required
      "id_city": 1,
      //Тип обратной связи: 1 - Ошибка в приложении, 2 - Неверные условия акции, 3 - Другое: number, required
      "type": 1,
      //Содержание обратной связи (описание): string, required
      "description": "Нету категории: часы"
    }
