description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат успешности отправки обратной связи: true - обратная связь отправлена, false - нет: bool
          "succces": true
        }
      }
