application/json:
  example: |
    {
      //Идентификатор пользователя: string, required
      "id": "BF4585465460D",
      //Идентификатор города: number, required
      "id_city": 1,
      //Оценка приложения пользователем от 1 до 5: number, required
      "star": 5,
      //Тип операционной системы приложения: string, required
      "os": "android",
      //Версия приложения: string, required
      "version_app": "1.0.0.0",
      //Причина низкой оценки: string, required
      "description": "Приложение весит 100 mb"
    }
