description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат отправки оценки: true - оценка отправлена, false - нет: bool
          "succces": true
        }
      }
