application/json:
  example: |
    {
      //Идентификатор пользователя: string, required
      "id": "BF4585465460D",
      //Идентификатор клиента: string, required
      "id_client": "DKWPDKg54DDS",
      //Идентификатор города: number, required
      "id_city": 1,
      //Флаг, указывающий операцию: true - пользователь подписался на клиента, false - пользователь отписался от клиента: bool
      "subscribe": true
    }
