description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат: true - операция выполнена успешно, false - неуспешно: bool
          "success": "true"
        }
      }
