description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат проверки на обновление категорий: bool
          //Если "isGet" = 1, то ,если "success" = true, то обновить категории нужно, иначе, если "success" = false, то обновлять категории не надо.
          //Если "isGet" = 2, то если "success" = true, флаг удачно снят, иначе, если "success" = false, то произошла непредвиденная ошибка.
          "succces": true
        }
      }
