description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
            //Результат отправки клика: true - отправка совершена, false - нет: bool
            "success": true
          }
      }
