description: |
  Выполнение запроса прошло с ошибкой.
  Коды ошибок:
    (10): Произошла ошибка сервера.
    (20): Отправлены некорректные данные.
    (30): Данные не найдены.
body:
  application/json:
    example: |
      {
        "error": {
          //Код ошибки: number
          "code": 20,
          //Сообщение ошибки: string
          "message": "Отправлены некорректные данные."
          }
      }
