description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат проведения операции лайка/дизлайка: true - операция прошла успешно, false - нет: bool
          "success": true
        }
      }
