description: Успешное выполнение запроса.
body:
  application/json:
    example: |
      {
        "response": {
          //Результат успеха отправки токена: true - отправка прошла успешно, false - нет: bool
          "succces": true
        }
      }
